services:
  # Backend API Service
  - type: web
    name: farsitranscriber-api
    env: node
    branch: server
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false

  # Frontend Service
  - type: static
    name: farsitranscriber
    env: static
    branch: master
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://farsitranscriber-api.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://farsitranscriber-api.onrender.com
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type, Authorization, Accept
