services:
  # Backend API Service
  - type: web
    name: farsitranscriber-api
    env: node
    branch: server
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false

  # Frontend Service
  - type: web
    name: farsitranscriber
    env: node
    branch: master
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://farsitranscriber-api.onrender.com
