name: Transcription API

on:
  issues:
    types: [opened]

jobs:
  transcribe:
    if: contains(github.event.issue.labels.*.name, 'transcription-request')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Process Transcription Request
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the audio data from the issue body
          AUDIO_DATA=$(echo '${{ github.event.issue.body }}' | jq -r '.audioData')
          
          # Decode base64 to file
          echo $AUDIO_DATA | base64 -d > audio.ogg
          
          # Call OpenAI API
          RESPONSE=$(curl -X POST https://api.openai.com/v1/audio/transcriptions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: multipart/form-data" \
            -F file=@audio.ogg \
            -F model="whisper-1" \
            -F language="fa")
          
          # Update the issue with the transcription
          gh issue comment "${{ github.event.issue.number }}" --body "$RESPONSE"
          gh issue edit "${{ github.event.issue.number }}" --add-label "transcription-complete"
